remote_theme: pages-themes/midnight@v0.2.0
title: Rating the Recipe: A Data Story
description: Investigating whether sugary recipes receive lower ratings on Food.com using statistical analysis and predictive modeling
plugins:
- jekyll-remote-theme
